#!/bin/sh

has_service() {
    dbus-send --session --print-reply \
        --dest=org.freedesktop.DBus \
        /org/freedesktop/DBus \
        org.freedesktop.DBus.NameHasOwner \
        string:com.feralinteractive.GameMode 2>/dev/null | grep -q 'boolean true'
}

if ! has_service; then
    gamemoded -d >"${XDG_RUNTIME_DIR:-/tmp}/cpak-gamemode.log" 2>&1 &
    attempts=0
    while ! has_service && [ "$attempts" -lt 20 ]; do
        sleep 0.05
        attempts=$((attempts + 1))
    done
fi

gamemode_lib_path="${CPAK_ROOTFS:-}/usr/lib/cpak-gamemode/\$LIB"

exec env \
    LD_LIBRARY_PATH="${gamemode_lib_path}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}" \
    LD_PRELOAD="${gamemode_lib_path}/libgamemode.so:${gamemode_lib_path}/libgamemodeauto.so.0${LD_PRELOAD:+:$LD_PRELOAD}" \
    "$@"
